name: Sync Fork

on:
  schedule:
    - cron: '30 */12 * * *'      # every 12 hours
  workflow_dispatch:          # on button click

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync upstream 

    steps:
    - name: Checkout master
      uses: actions/checkout@v2
      with:
        ref: master
        
    - name: Pull upstream 
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v2.2
      with:
        upstream_repository: easy2view/epoch-news
        upstream_branch: master
        target_branch: master
